  
cb_edit_account_form:
    pattern: /account/{id}
    defaults: {_controller: CBAccountBundle:Form:edit}

cb_new_account_form:
    pattern:  /account
    defaults: { _controller: CBAccountBundle:Form:index}