cb_dashboard:
  pattern: /dashboard
  defaults: {_controller: CBAccountBundle:Dashboard:index}

cb_new_announcement_form:
    pattern: /announcement
    defaults: {_controller: CBAccountBundle:Announcement:create}
    
cb_edit_account_form:
    pattern: /account/{id}
    defaults: {_controller: CBAccountBundle:Account:edit}

cb_new_account_form:
    pattern:  /account
    defaults: { _controller: CBAccountBundle:Account:create}