parameters:
#    cb_account.example.class: CB\AccountBundle\Example

services:
#    cb_account.example:
#        class: %cb_account.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
