parameters:
#    cb_reviewer.example.class: CB\ReviewerBundle\Example

services:
#    cb_reviewer.example:
#        class: %cb_reviewer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
