cb_test:
    resource: "@CBTestBundle/Resources/config/routing.yml"
    prefix:   /

cb_admin:
    resource: "@CBAdminBundle/Resources/config/routing.yml"
    prefix:   /

cb_main:
    resource: "@CBMainBundle/Resources/config/routing.yml"
    prefix:   /

cb_proponent:
    resource: "@CBProponentBundle/Resources/config/routing.yml"
    prefix:   /

cb_reviewer:
    resource: "@CBReviewerBundle/Resources/config/routing.yml"
    prefix:   /

cb_grant:
    resource: "@CBGrantBundle/Resources/config/routing.yml"
    prefix:   /

cb_project:
    resource: "@CBProjectBundle/Resources/config/routing.yml"
    prefix:   /

cb_account:
    resource: "@CBAccountBundle/Resources/config/routing.yml"
    prefix:   /

logout:
    path:   /logout
    
login:
    path:     /login
    defaults: { _controller: CBAccountBundle:Security:login }
    
login_check:
    path: /login_check