
cb_approve_project_in_phase:
  pattern: /approve/{instance}/{project}
  defaults: {_controller: CBGrantBundle:PhaseInstance:approve }

cb_select_grant_template:
  pattern: /grant/{id}/instance/select
  defaults: { _controller: CBGrantBundle:GrantInstance:select }

cb_create_grant_instance:
  pattern: /grant/{id}/instance/create
  defaults: { _controller: CBGrantBundle:GrantInstance:create }

cb_add_grant_template:
  pattern: /{grant}/template/add
  defaults: {_controller: CBGrantBundle:Grant:addTemplate}

cb_grant_permalink:
  pattern: /{user}/grant/{id}/info
  defaults: { _controller: CBGrantBundle:Grant:view }

cb_submit_project_to_phase_instance:
  pattern: /submit/phase/{phase}/{project}
  defaults: {_controller: CBGrantBundle:PhaseInstance:submitProject}

cb_phase_instance_permalink:
  pattern: /{user}/phase/{phase}/{project}
  defaults: { _controller: CBGrantBundle:PhaseInstance:view, project: 0 }

cb_grant_instance_permalink:
  pattern: /{user}/grant/{grant}/{project}
  defaults: { _controller: CBGrantBundle:GrantInstance:view, project: 0 }

cb_add_project_to_cycle:
  pattern: /grant/{id}/project/add
  defaults: {_controller: CBGrantBundle:GrantInstance:addProject }

cb_view_submitted_proposals:
  pattern: /grant/phase/instance/{id}
  defaults: {_controller: CBGrantBundle:PhaseInstance:view }


cb_grant_instance:
  pattern: /grant/{id}/instance
  defaults: { _controller: CBGrantBundle:GrantInstance:view }

funder_create_grant:
    pattern: /grant/create
    defaults: { _controller: CBGrantBundle:Create:grant }

cb_all_grants:
  pattern: /grants
  defaults: { _controller: CBGrantBundle:Grant:viewAll }

