parameters:
#    cb_proponent.example.class: CB\ProponentBundle\Example

services:
#    cb_proponent.example:
#        class: %cb_proponent.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
