
cb_proponent_upload_document:
  pattern: /document/{document}/{phase}/{project}
  defaults: {_controller: CBProjectBundle:Document:create}

cb_project_permalink:
  pattern: /{user}/project/{id}
  defaults: { _controller: CBProjectBundle:Project:view }

cb_create_project:
  pattern: /project/create
  defaults: { _controller: CBProjectBundle:Project:create }

cb_project_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: CBProjectBundle:Default:index }
