parameters:
#    cb_admin.example.class: CB\AdminBundle\Example

services:
#    cb_admin.example:
#        class: %cb_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
